trigger: none

parameters:
  - name: azureSubscription
    type: string

steps:
- task: AzureCLI@2
  displayName: 'Convert Bicep File to ARM template'
  inputs: 
    azureSubscription: ${{ parameters.azureSubscription }}
    inlineScript: |
      az bicep build --file bicepdeploy.bicep
    scriptLocation: inlineScript
    scriptType: bash
- task: AzurePowerShell@5 
  displayName: 'Deploy Template'
  inputs: 
    azureSubscription: ${{ parameters.azureSubscription }}
    Inline: |
      .\deploy.ps1 -DeploymentFile .\server1.json -TemplateFile .\bicepdeploy.json
